mygh/home/urls.py
from django.conf.urls import include, url

urlpatterns = [
	url(r'^history/$', 'home.views.history', name='history'),
	url(r'^about/$', 'home.views.about', name='about'),
]

mygh/mygh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'home.views.main', name='main'),
    url(r'^node/', include('nodes.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^room/', include('rooms.urls')),
    url(r'^account/', include('accounts.urls')),
]

mygh/nodes/urls.py
from django.conf.urls import include, url


from djgeojson.views import GeoJSONLayerView
from .models import GPSCoordinate, PixelCoordinate

urlpatterns = [
	url(r'^$', 'nodes.views.node', name='node'),
	url(r'^add_node/$', 'nodes.views.add_node', name='add_node'),
	url(r'^delete_node/$','nodes.views.delete_node', name='delete_node'),
	url(r'^modify_node/$', 'nodes.views.modify_node', name='modify_node'),
	url(r'^add_batt/$', 'nodes.views.add_batt', name='add_batt'),
	# sensor basis
    url(r'^node_properties/$', 'nodes.views.node_properties', name='node_properties'),

    # node's real position
    url(r'^node_info/$', 'nodes.views.node_info', name='node_info'),
    url(r'^node_list_pixel/$', 'nodes.views.node_list_pixel', name='node_list_pixel'),  

    # node coordinate by using geojson
    url(r'^gps.geojson$', GeoJSONLayerView.as_view(model=GPSCoordinate, properties=('node_number'),), name='data'),
    url(r'^pixel.geojson$', GeoJSONLayerView.as_view(model=PixelCoordinate, properties=('node_number', 'room_id'),), name='pixel'),
]

mygh/nodes/models.py
from django.db import models
from django.utils.encoding import smart_unicode

from rooms.models import Room
from djgeojson.fields import PointField

class SensorBasis(models.Model):
	batt = models.FloatField(null=True)
	temp = models.FloatField(null=True)
	hum = models.FloatField(null=True)
	src = models.IntegerField()
	dst = models.IntegerField()
	received_date = models.DateTimeField()
	remain_life = models.FloatField(null=True, default='400')
	# type:0 - default with longer life
	# type:1 - longer life battery
	# type:2 - shorter life battery
	batt_type = models.IntegerField(default=0)

	def __unicode__(self):
		return "Battery number:" + smart_unicode(self.src)

#Battery table
class Battery(models.Model):
	LOW = 'LOW'
	NORMAL = 'NOR'
	BATTERY_STATUS = (
		(LOW, 'Low'),
		(NORMAL, 'Normal'),
	)
	number = models.CharField(max_length=20, null=False, blank=False, default = 'B232')
	status = models.CharField(max_length=3, 
								choices = BATTERY_STATUS, 
								default = NORMAL)

	def natural_key(self):
		return (self.pk, self.number)

	def __unicode__(self):
		return "Battery number:" + smart_unicode(self.number)

#Nodes real location
class NodeLocation(models.Model):
	top = models.FloatField()
	left = models.FloatField()
	height = models.FloatField()
	room = models.ForeignKey(Room)
 
	def natural_key(self):
		return (self.top, self.left, self.height, self.room.rnumber)

	def __unicode__(self):
		return  "Node Location: room = " + smart_unicode(self.room)

#Nodes
class Node(models.Model):
	number = models.CharField(max_length=20, null=False, blank=False, default = 'N232')
	battery = models.OneToOneField(Battery)
	nodelocation = models.OneToOneField(NodeLocation)

	def __unicode__(self):
		return "Node number: " + smart_unicode(self.number)

#Nodes PixelCoordinate
class PixelCoordinate(models.Model):
	node = models.ForeignKey(Node)
	# This field is only for passing node id throught geojson plugin, I couldn't find another way to do it
	node_number = models.CharField(max_length=20) 
	room_id = models.IntegerField(unique=False)
	geom = PointField()

	def __unicode__(self):
		return "location: x:" + smart_unicode(self.geom)

#Nodes GPSCoordinate
class GPSCoordinate(models.Model):
	node = models.OneToOneField(Node)
	node_number = models.CharField(max_length=20)
	geom = PointField()

	def __unicode__(self):
		return "Node GPS: " + smart_unicode(self.geom)

mygh/nodes/views.py
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.db.models import Max, Count
from django.views.decorators.csrf import csrf_exempt

from django.core import serializers
from djgeojson.serializers import Serializer as GeoJSONSerializer
from .form import AddNodeForm, AddBatteryForm, ModifyNodeForm
from .models import *
from rooms.models import *
from home.models import *

import utm
import math
import json

def modify_node(request):
    if request.method == 'POST':
        form = ModifyNodeForm(request.POST or None)
        if form.is_valid():
            data = form.cleaned_data

            node_id = data['node_id']
            battery_id = data['battery']
            room_number = data['room']
            top = data['top']
            left = data['left']
            height = data['height']

            node = Node.objects.get(pk = node_id)
            # recaculate coordinate
            gps_cor = GPSCoordinate.objects.get(node = node)
            pixel_cor = PixelCoordinate.objects.filter(node = node)

            room = Room.objects.filter(rnumber = room_number)
            battery = Battery.objects.get(pk = battery_id)
            node.battery = battery

            nodelocation = NodeLocation.objects.get(pk = node.nodelocation.pk)
            nodelocation.top = top
            nodelocation.left = left
            nodelocation.height = height
            nodelocation.room = room[0]
            nodelocation.save()

            node.nodelocation = nodelocation
            node.save()

            cal_gps_location(room[0], node, gps_cor)
            cal_pixel_location(room[0], node, pixel_cor)

            history = HistoryRecord()
            history.nnumber = node.number
            history.operation = 'Modify'
            history.battery_number = battery.number
            history.rumber = room[0].rnumber
            history.location_top = top
            history.location_left = left
            history.location_height = height
            history.save()

            return HttpResponseRedirect('/')
    else:
        form = ModifyNodeForm()

    return render(request, 'modify_node.html', {'form': form})

# node list in each background
@csrf_exempt
def node_list_pixel(request):
	bg_name = request.POST.get('bg_name', '')

	# query room list by the bg name, could be a list
	rooms = Background.objects.filter(name = bg_name)

	node_list_pixel = []
	for room in rooms:
		nodes = PixelCoordinate.objects.filter(room_id = room.pk)
		node_list_pixel.append(nodes)
	
	snode_list_pixel = GeoJSONSerializer().serialize(node_list_pixel, use_natural_keys=True, with_modelname=False)
	return JsonResponse(snode_list_pixel, safe=False)	

@csrf_exempt
def delete_node(request):
    cor_id = request.POST.get('cor_id', '')
    cur_view = request.POST.get('cur_view', '')

    if cur_view == 'mapMenu':
    	gps_cor = GPSCoordinate.objects.get(pk=cor_id)
    	node_id = gps_cor.node.pk
    else:
    	pixel_cor = PixelCoordinate.objects.get(pk=cor_id)
    	node_id = pixel_cor.node.pk
    
    node = Node.objects.get(pk=node_id);
    battery = Battery.objects.get(pk=node.battery.pk)
    room = Room.objects.get(pk=node.nodelocation.room_id) 

    history = HistoryRecord()
    history.nnumber = node.number
    history.operation = 'Delete'
    history.battery_number = battery.number
    history.rumber = room.rnumber
    history.location_top = node.nodelocation.top
    history.location_left = node.nodelocation.left
    history.location_height = node.nodelocation.height
    history.save()

    node.delete()
    node.nodelocation.delete()

    return HttpResponseRedirect('/')

@csrf_exempt
def node_info(request):
    nodes = Node.objects.all()
    snodes = serializers.serialize('json', nodes, use_natural_foreign_keys=True)

    return JsonResponse(snodes, safe=False)	

def node_properties(request):
	last = last_basis()
	# print last
	s = serializers.serialize('json', last)

	return JsonResponse(s, safe=False)

def last_basis():
	# I'm sure there is a better approach to do it...
	# query sensor group by node src.
	nodes = SensorBasis.objects.values('src').annotate(scount=Count('src'))
	
	# list with most recent received packet for each node.
	last = []
	for n in nodes:
		# get node id
		nid = n['src']
		# queryset with lastest time, we only need information from last packet
		l = SensorBasis.objects.filter(src=nid).aggregate(Max('received_date'))
		# instance which filtered by src and most recent received time 
		v = SensorBasis.objects.get(src=nid, received_date = l['received_date__max'])
		# write every instance into list
		last.append(v)

	return last	

def add_batt(request):
    if request.method == 'POST':
        form = AddBatteryForm(request.POST or None)
        if form.is_valid():
            data = form.cleaned_data

            battery = Battery()
            battery.number = data['number']
            battery.save()
 			# redirect to home page
            return HttpResponseRedirect('/')
    else:
        form = AddBatteryForm()

    return render(request, 'add_batt.html', {'form': form})	

def node(request):
	nodes = Node.objects.all()

	nodes_data = {
		"node_detail" : nodes
	}

	return render_to_response("node.html", 
							nodes_data,
							context_instance=RequestContext(request))

def get_nodes_cor(request):
	# select data from location and basis
	geo = serializers.serialize('json', NodeLocation.objects.all())

	return JsonResponse(geo, safe=False)

def add_node(request):
    if request.method == 'POST':
        form = AddNodeForm(request.POST or None)
        if form.is_valid():
            data = form.cleaned_data

            number = data['number']
            room_number = data['room']
            battery_id = data['battery']

            top = data['top']         
            left = data['left']
            height = data['height']

            # query room object
            room = Room.objects.filter(rnumber = room_number)
           
            # save nodeLocation
            nodeLocation = NodeLocation()
            nodeLocation.top = top
            nodeLocation.left = left
            nodeLocation.height = height
            nodeLocation.room = room[0]
            nodeLocation.save()

            # save node
            node = Node()
            battery = Battery.objects.get(pk = battery_id)
            node.battery = battery
            node.number = number
            node.nodelocation = nodeLocation
            node.save()
            
            # calculate and save gpslocation
            cal_gps_location(room[0], node, None)

            # calculate and save pixellocation
            cal_pixel_location(room[0], node, None)

            history = HistoryRecord()
            history.nnumber = number
            history.operation = 'Add'
            history.battery_number = battery.number
            history.rumber = room[0].rnumber
            history.location_top = top
            history.location_left = left
            history.location_height = height
            history.save()

 			# redirect to home page
            return HttpResponseRedirect('/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AddNodeForm()

    return render(request, 'add_node.html', {'form': form})	

# Calculate node's pixel coordinate and save to database
# one node may has several pixel coordinates depends on image background
def cal_pixel_location(room, node, pixel_cor):
	top = node.nodelocation.top
	left = node.nodelocation.left

	# room's size
	width = room.width
	length = room.length

	# room list with the same number as the one user chose
	rooms = Room.objects.filter(rnumber = room.rnumber)

	# make a pixel coordinate list by using the room id 
	# query all the instances first
	roompixellocations = RoomPixelLocation.objects.all()

	pixelList = []
	for plocation in roompixellocations:
		for r in rooms:
			if r.pk == plocation.room.pk:
				# add to a list
				pixelList.append(plocation)

	# room's pixel location in current image
	# roompixellocation = RoomPixelLocation.objects.get(room = room.pk)
	i = 0
	for pl in pixelList:
		print 'room id=' + str(pl.room_id)
		# left-top coordinate
		pixel_x_lt = pl.pixel_x_lt
		pixel_y_lt = pl.pixel_y_lt

		# right-bottom coordinate
		pixel_x_rb = pl.pixel_x_rb
		pixel_y_rb = pl.pixel_y_rb

		# now we have enough information for calculating the node's pixel coordinate in current imgae
		# formular: x = RoomLT_X + node_left / room_real_width * room_pixel_width
		#          y = RoomLT_Y - node_top / room_real_length * room_pixel_length
		x = pixel_x_lt + float(left) / width * math.fabs(pixel_x_rb - pixel_x_lt)
		y = pixel_y_lt - float(top) / length * math.fabs(pixel_y_rb - pixel_y_lt)
        
		if pixel_cor is None:
			pixelLocation = PixelCoordinate()
		else:
			pixelLocation = pixel_cor[i]

		i += 1
		pixelLocation.node = node
		pixelLocation.geom = {'type': 'Point', 'coordinates': [x, y]}
		pixelLocation.room_id = pl.room.pk
		pixelLocation.node_number = node.number
		pixelLocation.save()

# Calculate node's gps coordinate
# 1. Calculate node's UTM coordinate by using relative parameters
# 2. Transform it to Geographic coordinate. (Latitude/longitude
def cal_gps_location(room, node, gps_cor):
	top = node.nodelocation.top
	left = node.nodelocation.left

	roomgpslocation	= RoomGPSLocation.objects.get(room = room.pk)
	#TODO: raise an execption here

	# room's gps location, we only need two points
	# left-top coordinate
	latitute_lt = roomgpslocation.latitute_lt
	longitute_lt = roomgpslocation.longitute_lt

	# left-bottom coordinate
	latitute_lb = roomgpslocation.latitute_lb
	longitute_lb = roomgpslocation.longitute_lb

	# room left-top UTM coordinate
	# I don't realy care about zone number and letter, since we just in very short distance, keep them just in case.
	# (EASTING, NORTHING, ZONE NUMBER, ZONE LETTER).

mygh/nodes/templates/add_batt.html
{% extends 'base.html' %}
{% block content %}

<div class="container add-batt">
	<div class="row centered">
		<div class="col-md-6 col-md-offset-3">
		  <div class="error"></div>
		  <h3>Add Battery</h3>
			<form class="form-add-batt" method="post" action="/node/add_batt/">
			{% csrf_token %}
			<table class="table">
				{{ form.as_table }}
			</table>
			<button type="submit" class="btn btn-primary btn-gh btn-add-batt">Add</button>
			
			</form>
		  </div>
	</div>
</div>
{% endblock %}

mygh/nodes/templates/add_node.html
{% extends 'base.html' %}
{% block content %}
<div class="container add-node">
	<div class="row centered">
		<div class="col-md-6 col-md-offset-3">
		  <div class="error"></div>
		  <h3>Add Node</h3>
			<form class="form-add-node" method="post" action="/node/add_node/">
			{% csrf_token %}
			<table class="table">
				{{ form.as_table }}
			</table>
			<button type="submit" class="btn btn-primary btn-gh btn-add-node">Add</button>
			
			</form>
		  </div>
	</div>
</div>
{% endblock %}

mygh/nodes/templates/modify_node.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container add-node">
	<div class="row centered">
		<div class="col-md-6 col-md-offset-3">
		<div class="error"></div>
		  <h3 class="title-modify-node">Modify Node</h3>
       		<form class="form-modify-node" method="post" action="/node/modify_node/">
			{% csrf_token %}
			<table class="table">
			  {{form.as_table}}				
			  <tr class="centered">
				<td colspan="2"> 
					<button type="submit" class="btn btn-primary btn-modify-node">Modify</button>
				</td>
			  </tr>
			</table>
			</form>
		  </div>
	</div>
</div>
<script type="text/javascript" src="{% static 'js/sessvars.js' %}"></script>
<script type="text/javascript">
	// let's show data passed from main page into the form
	var node = sessvars.node;

	if(node !== undefined){
		var title = "Modify Node " + node.number;

		$('#id_node_id').val(node.id);
		$('.title-modify-node').html(title);

		// set the value with same text
		$('#id_room option:contains(' + node.room + ')').each(function(){
		    if ($(this).text() == node.room) {
		        $(this).attr('selected', 'selected');
		        return false;
		    }
		    return true;
		});

		$('#id_battery option:contains(' + node.batt[1] + ')').each(function(){
		    if ($(this).text() == node.batt[1]) {
		        $(this).attr('selected', 'selected');
		        return false;
		    }
		    return true;
		});


		$('#id_top').val(node.top);
		$('#id_left').val(node.left);
		$('#id_height').val(node.height);
	}
	
	$('.btn-modify-node').click(function(){
	  var node_id = sessvars.id;
	  // get values after modifying
	     
	});


	$.ajax({
    	url : "/node/node_info",
    	type: "GET",
    	success: function(info)
    	{
    		var json_obj = $.parseJSON(info);

      		for (var i in json_obj){
        		var battery = json_obj[i].fields.battery; 

        		// removed used battery options.
        		$("#id_battery > option").each(function() {
        			if(this.value == battery[0] && this.value != node.batt[0]){
        				this.remove();
        			}
      			});
      		}

    	},
    	error: function (info)
    	{
       		//TODO: some prompt for error?
    	}
  	});
</script>
{% endblock %}

mygh/nodes/templates/node.html
{% extends 'base.html' %}
{% block content %}
{% load endless %}
<div class="container node">
	<div class="row">
		<div class="col-md-12">
		<h2>Nodes</h2>
		{% paginate node_detail %}
		<div class="show-pages">		
		{% show_pages %}
		</div>
		<table class="table table-striped table-hover node-list">
			<tr>
				<th>ID</th>
				<th>Number</th>
				<th>Battery</th>
				<th>Room</th>
				<th>Location</th>
				<th>View Map</th>
			</tr>	

		{% for detail in node_detail %}
			<tr>
				<td>{{detail.id}}</td>
				<td>{{detail.number}}</td>
				<td>{{detail.battery.number}}</td>
				<td>{{detail.nodelocation.room.rnumber}}</td>
				<td>
					<b>Top:</b> {{detail.nodelocation.top}} <br />
					<b>Left:</b> {{detail.nodelocation.left}} <br />
					<b>Height:</b> {{detail.nodelocation.height}} <br />
				</td>
				<td>
					<button type="button" class="btn btn-default btn-zoom-{{detail.id}}" value="{{detail.number}}">Map</button>
				</td>
			</tr>	
		{% endfor %}
		</table>
		
		</div>
	</div>
</div>

<script type="text/javascript">	
	$("body").on('click', 'button', function(event) {
	  var button = $(event.target);
	  // here we pass feature id to main page inorder to show popover there.
      var url = "/?src=" + encodeURIComponent(button.val());
	  window.location.href = url;
	});
</script>
{% endblock %}